version: '3.3'

services:

  nestjs:
      # image: nestjscontainer2:latest

      build: ../

      container_name: nestjs
      
      volumes:
         - .:/home/dev/
           
      command: "npm run start:dev"
        
      ports:
         - 3000:3000
      
      env_file:
         - env.envar

      depends_on:
         - postgres

  postgres:
   
      image: postgres:14-alpine
      
      container_name: postgres
         
      env_file:
         - env.envar
      
      expose:
         - "${POSTGRES_PORT}/tcp"

#primero se debe iniciar el comando "docker-compose run nestjs bash"
#y luego que se accesa al contenedor se deben instalar los paquete con el comando "npm install"
#por ultimo se debe salir del contenedor, eliminar los contenedores anteriores con "docker-comopse down"
#y luego ejecutar "docker-compose up -d" para que inicien los contenedores en background
    