version: '3.3'

services:

  nestjs:
  
      build: ../

      container_name: nestjs
      
      volumes:
         - .:/home/dev/
           
      command: bash -c "npm install && npm run start:dev"
        
      ports:
         - 3000:3000
      
      env_file:
         - env.envar

      depends_on:
         - mongo

  mongo:
   
      image: mongo:4.4.6
      
      container_name: mongo
         
      env_file:
         - env.envar
      
      expose:
         - "27017/tcp"

#   mongo-express:
#       image: mongo-express
#       restart: unless-stopped
#       ports:
#          - 8081:8081
#       environment:
#          ME_CONFIG_MONGODB_ADMINUSERNAME: test
#          ME_CONFIG_MONGODB_ADMINPASSWORD: test
#          ME_CONFIG_MONGODB_URL: mongodb://test:test@mongo:27017/
   
#       depends_on:
#          - mongo
    